<?php

namespace Jeovajr\ResourceWizard\Services;

final class DefaultColumns
{
    public static function get(): array
    {
        return [
            'id' => [
                'db_name' => 'id',
                'db_type' => 'bigIncrements',
                'db_length' => null,
                'db_nullable' => false,
                'db_default' => null,
                'db_unique' => null,
                'db_index' => null,
                'db_unsigned' => null,
                'db_comment' => 'Primary Key',
                'model_hidden' => false,
                'model_editable' => false,
                'model_searchable' => false,
                'model_filterable' => true,
                'model_sortable' => true,
                'request_validation' => [
                    'store' => null,
                    'update' => null,
                    'messages' => [],
                ],
                'resource_name' => 'ID',
            ],
            'created_at' => [
                'db_name' => 'created_at',
                'db_type' => 'timestampTz',
                'db_length' => null,
                'db_nullable' => false,
                'db_default' => null,
                'db_unique' => null,
                'db_index' => null,
                'db_unsigned' => null,
                'db_comment' => 'When the record was created',
                'model_hidden' => false,
                'model_editable' => false,
                'model_searchable' => false,
                'model_filterable' => true,
                'model_sortable' => true,
                'request_validation' => [
                    'store' => null,
                    'update' => null,
                    'messages' => [],
                ],
                'resource_name' => 'Created At',
            ],
            'created_by' => [
                'db_name' => 'created_by',
                'db_type' => config('resource-wizard.user.id.type'),
                'db_length' => null,
                'db_nullable' => false,
                'db_default' => null,
                'db_unique' => null,
                'db_index' => null,
                'db_unsigned' => null,
                'db_comment' => 'Who created the record',
                'model_hidden' => false,
                'model_editable' => false,
                'model_searchable' => false,
                'model_filterable' => true,
                'model_sortable' => true,
                'request_validation' => [
                    'store' => null,
                    'update' => null,
                    'messages' => [],
                ],
                'resource_name' => 'Created By',
            ],
            'updated_at' => [
                'db_name' => 'updated_at',
                'db_type' => 'timestampTz',
                'db_length' => null,
                'db_nullable' => true,
                'db_default' => null,
                'db_unique' => null,
                'db_index' => null,
                'db_unsigned' => null,
                'db_comment' => 'When the record was last updated',
                'model_hidden' => false,
                'model_editable' => false,
                'model_searchable' => false,
                'model_filterable' => true,
                'model_sortable' => true,
                'request_validation' => [
                    'store' => null,
                    'update' => null,
                    'messages' => [],
                ],
                'resource_name' => 'Updated At',
            ],
            'updated_by' => [
                'db_name' => 'updated_by',
                'db_type' => config('resource-wizard.user.id.type'),
                'db_length' => null,
                'db_nullable' => true,
                'db_default' => null,
                'db_unique' => null,
                'db_index' => null,
                'db_unsigned' => null,
                'db_comment' => 'Who last updated the record',
                'model_hidden' => false,
                'model_editable' => false,
                'model_searchable' => false,
                'model_filterable' => true,
                'model_sortable' => true,
                'request_validation' => [
                    'store' => null,
                    'update' => null,
                    'messages' => [],
                ],
                'resource_name' => 'Updated By',
            ],
            'deleted_at' => [
                'db_name' => 'deleted_at',
                'db_type' => 'timestampTz',
                'db_length' => null,
                'db_nullable' => true,
                'db_default' => null,
                'db_unique' => null,
                'db_index' => null,
                'db_unsigned' => null,
                'db_comment' => 'When the record was deleted',
                'model_hidden' => false,
                'model_editable' => false,
                'model_searchable' => false,
                'model_filterable' => true,
                'model_sortable' => true,
                'request_validation' => [
                    'store' => null,
                    'update' => null,
                    'messages' => [],
                ],
                'resource_name' => 'Deleted At',
            ],
            'locked_at' => [
                'db_name' => 'locked_at',
                'db_type' => 'timestampTz',
                'db_length' => null,
                'db_nullable' => true,
                'db_default' => null,
                'db_unique' => null,
                'db_index' => null,
                'db_unsigned' => null,
                'db_comment' => 'When the record was locked',
                'model_hidden' => false,
                'model_editable' => false,
                'model_searchable' => false,
                'model_filterable' => true,
                'model_sortable' => true,
                'request_validation' => [
                    'store' => null,
                    'update' => null,
                    'messages' => [],
                ],
                'resource_name' => 'Locked At',
            ],
            'locked_by' => [
                'db_name' => 'locked_by',
                'db_type' => config('resource-wizard.user.id.type'),
                'db_length' => null,
                'db_nullable' => true,
                'db_default' => null,
                'db_unique' => null,
                'db_index' => null,
                'db_unsigned' => null,
                'db_comment' => 'Who locked the record',
                'model_hidden' => false,
                'model_editable' => false,
                'model_searchable' => false,
                'model_filterable' => true,
                'model_sortable' => true,
                'request_validation' => [
                    'store' => null,
                    'update' => null,
                    'messages' => [],
                ],
                'resource_name' => 'Locked By',
            ],
        ];
    }
}
